# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='notifications_count',
            new_name='notification_count',
        ),
    ]
