# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 19:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_myuser_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=15)),
                ('notification_media', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
                ('time_of_creation', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='notification_count',
            new_name='new_notification_count',
        ),
        migrations.AddField(
            model_name='notification',
            name='notifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
