# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20160618_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
