# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-18 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20160618_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='notified_user',
        ),
    ]
