# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-18 17:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20160618_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notified_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notified_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
