# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-20 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20160618_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
