# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-22 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20160620_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='box_status',
            field=models.IntegerField(default=0),
        ),
    ]
